/**************************************************************************//**
 * @file      version.h
 * @brief     Version header (autogenerated by cmake)
 *
 * @author    ymaran
 * @date      3.4.2023
 * @copyright 
 *****************************************************************************/

#pragma once

/******************************************************************************
 * Project version constants
 *****************************************************************************/
#define PROJECT_VERSION_MAJOR 1
#define PROJECT_VERSION_MINOR 0
#define PROJECT_VERSION_PATCH 0
#define PROJECT_VERSION "1.0.0"
